version: '2'
services:
  emblem-web-server:
    build: ./server/
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/emblem-web
    depends_on:
     - emblem-db
    links:
     - emblem-db
    command: bash -c "npm install && nodemon -L server.js"
  emblem-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=emblem
