version: '2'
services:
    emblem-web:
        build: ./server/
        ports:
         - "3000:3000"
        volumes:
         - .:/usr/emblem-web
        depends_on:
         - emblem-db
    emblem-db:
        image: postgres