#v1 for compatability with Circle CI
emblem-web-client:
  build: client
  ports:
   - "8080:8080"
   - "80:80"
  volumes:
   - ./client:/usr/client
   # Mount the node folders as 'Empty' on Docker container
   # This prevents symlink issues between the container and the host filesystem
   - /usr/client/node_modules
  environment:
   - HOST_MODE=${HOST_MODE}
  command: npm start
emblem-web-api:
  build: api
  ports:
   - "3000:3000"
  volumes:
   - ./api:/usr/api
   - /usr/api/node_modules
  environment:
   - SESSION_SECRET=${SESSION_SECRET}
   - FACEBOOK_ID=${FACEBOOK_ID}
   - FACEBOOK_SECRET=${FACEBOOK_SECRET}
   - AWS_ID=${AWS_ID}
   - AWS_SECRET=${AWS_SECRET}
   - HOST_MODE=${HOST_MODE}
   - HOST_SERVER=${HOST_SERVER}
  links:
   - emblem-db
  command: npm start
emblem-db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=emblem
  ports:
    - "5432:5432"
