version: '2'
services:
  emblem-web-server:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/emblem-web
    depends_on:
     - emblem-db
    links:
     - emblem-db
    command: npm start
  emblem-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=emblem
